/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coders.quickbill;

import javax.swing.JFrame;
import java.awt.Color;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.ImageIcon;
import static java.lang.Thread.sleep;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import static java.lang.Thread.sleep;
import java.sql.SQLException;

/**
 *
 * @author sunny
 */
public class Dashboard extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form Dashboard
     */
    public Dashboard() {
        initComponents();
        this.setIconImage(new ImageIcon(getClass().getResource("QB_Icon-32x32.png")).getImage());
        conn=javaconnect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblProductName = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        lblUser = new javax.swing.JLabel();
        lblProduct = new javax.swing.JLabel();
        lblSales = new javax.swing.JLabel();
        lblReports = new javax.swing.JLabel();
        lblSalesAccount = new javax.swing.JLabel();
        lblCustomers = new javax.swing.JLabel();
        lblAbout = new javax.swing.JLabel();
        lblDealersAccount = new javax.swing.JLabel();
        lblLicenseDetails = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuCompany = new javax.swing.JMenu();
        mnuManageCompanyDetails = new javax.swing.JMenuItem();
        mnuProducts = new javax.swing.JMenu();
        mnuDirectProductManagement = new javax.swing.JMenuItem();
        mnuPurchaseReturn = new javax.swing.JMenuItem();
        mnuPurchaseInward = new javax.swing.JMenuItem();
        mnuSales = new javax.swing.JMenu();
        mnuPosTerminal = new javax.swing.JMenuItem();
        mnuSalesReturn = new javax.swing.JMenuItem();
        mnuGST = new javax.swing.JMenu();
        mnuGSTRatesManagement = new javax.swing.JMenuItem();
        mnuReports = new javax.swing.JMenu();
        mnuSalesAccount = new javax.swing.JMenu();
        mnuCustomers = new javax.swing.JMenu();
        mnuDealerAccount = new javax.swing.JMenu();
        mnuAbout = new javax.swing.JMenu();
        mnuClose = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Coders QuickBill 2017");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        lblProductName.setFont(new java.awt.Font("Ubuntu", 1, 48)); // NOI18N
        lblProductName.setForeground(java.awt.Color.white);
        lblProductName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProductName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/ProductLogo.png"))); // NOI18N

        jPanel2.setBackground(new java.awt.Color(40, 40, 40));

        lblUser.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblUser.setForeground(java.awt.Color.white);
        lblUser.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblUser.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/manage_user.png"))); // NOI18N
        lblUser.setText("Company");
        lblUser.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblUser.setPreferredSize(new java.awt.Dimension(135, 150));
        lblUser.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblUser.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblUserMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblUserMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblUserMouseExited(evt);
            }
        });

        lblProduct.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblProduct.setForeground(java.awt.Color.white);
        lblProduct.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/product.png"))); // NOI18N
        lblProduct.setText("Products");
        lblProduct.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblProduct.setPreferredSize(new java.awt.Dimension(135, 150));
        lblProduct.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblProductMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblProductMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblProductMouseExited(evt);
            }
        });

        lblSales.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSales.setForeground(java.awt.Color.white);
        lblSales.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSales.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/sales.png"))); // NOI18N
        lblSales.setText("Sales");
        lblSales.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSales.setPreferredSize(new java.awt.Dimension(135, 150));
        lblSales.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSalesMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalesMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalesMouseEntered(evt);
            }
        });

        lblReports.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblReports.setForeground(java.awt.Color.white);
        lblReports.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblReports.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/data_table.png"))); // NOI18N
        lblReports.setText("Reports");
        lblReports.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblReports.setPreferredSize(new java.awt.Dimension(135, 150));
        lblReports.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblReports.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblReportsMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblReportsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblReportsMouseExited(evt);
            }
        });

        lblSalesAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblSalesAccount.setForeground(java.awt.Color.white);
        lblSalesAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblSalesAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/notebook.png"))); // NOI18N
        lblSalesAccount.setText("Sales Account");
        lblSalesAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblSalesAccount.setPreferredSize(new java.awt.Dimension(135, 150));
        lblSalesAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblSalesAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblSalesAccountMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblSalesAccountMouseExited(evt);
            }
        });

        lblCustomers.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblCustomers.setForeground(java.awt.Color.white);
        lblCustomers.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCustomers.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/Customer_Male_Light_128px_533992_easyiconnet.png"))); // NOI18N
        lblCustomers.setText("Customers");
        lblCustomers.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblCustomers.setPreferredSize(new java.awt.Dimension(135, 150));
        lblCustomers.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblCustomersMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblCustomersMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblCustomersMouseExited(evt);
            }
        });

        lblAbout.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblAbout.setForeground(java.awt.Color.white);
        lblAbout.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAbout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/help.png"))); // NOI18N
        lblAbout.setText("About");
        lblAbout.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblAbout.setPreferredSize(new java.awt.Dimension(135, 150));
        lblAbout.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblAbout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblAboutMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblAboutMouseExited(evt);
            }
        });

        lblDealersAccount.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lblDealersAccount.setForeground(java.awt.Color.white);
        lblDealersAccount.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDealersAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/dealer.png"))); // NOI18N
        lblDealersAccount.setText("Dealer Account");
        lblDealersAccount.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        lblDealersAccount.setPreferredSize(new java.awt.Dimension(135, 150));
        lblDealersAccount.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        lblDealersAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblDealersAccountMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lblDealersAccountMouseExited(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lblDealersAccountMouseEntered(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblSales, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblReports, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblSalesAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblCustomers, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblDealersAccount, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(lblAbout, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblProduct, javax.swing.GroupLayout.DEFAULT_SIZE, 171, Short.MAX_VALUE)
                    .addComponent(lblUser, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSales, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblSalesAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblCustomers, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblAbout, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblDealersAccount, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        lblLicenseDetails.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        lblLicenseDetails.setForeground(java.awt.Color.blue);
        lblLicenseDetails.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLicenseDetails, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblProductName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102)
                .addComponent(lblProductName)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblLicenseDetails, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(98, Short.MAX_VALUE))
        );

        jMenuBar1.setBackground(new java.awt.Color(53, 53, 53));
        jMenuBar1.setForeground(java.awt.Color.white);
        jMenuBar1.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N

        mnuCompany.setText("Company");
        mnuCompany.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N

        mnuManageCompanyDetails.setText("Manage Company Details");
        mnuManageCompanyDetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuManageCompanyDetailsActionPerformed(evt);
            }
        });
        mnuCompany.add(mnuManageCompanyDetails);

        jMenuBar1.add(mnuCompany);

        mnuProducts.setText("Purchase");
        mnuProducts.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        mnuProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuProductsMouseClicked(evt);
            }
        });

        mnuDirectProductManagement.setText("Direct Product Management");
        mnuDirectProductManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuDirectProductManagementActionPerformed(evt);
            }
        });
        mnuProducts.add(mnuDirectProductManagement);

        mnuPurchaseReturn.setText("Purchase Return");
        mnuPurchaseReturn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuPurchaseReturnMouseClicked(evt);
            }
        });
        mnuProducts.add(mnuPurchaseReturn);

        mnuPurchaseInward.setText("Purchase Invoice");
        mnuPurchaseInward.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPurchaseInwardActionPerformed(evt);
            }
        });
        mnuProducts.add(mnuPurchaseInward);

        jMenuBar1.add(mnuProducts);

        mnuSales.setText("Sales");
        mnuSales.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        mnuSales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuSalesMouseClicked(evt);
            }
        });

        mnuPosTerminal.setText("POS Terminal");
        mnuPosTerminal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuPosTerminalActionPerformed(evt);
            }
        });
        mnuSales.add(mnuPosTerminal);

        mnuSalesReturn.setText("Sales Return");
        mnuSalesReturn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuSalesReturnActionPerformed(evt);
            }
        });
        mnuSales.add(mnuSalesReturn);

        jMenuBar1.add(mnuSales);

        mnuGST.setText("GST");
        mnuGST.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuGSTMouseClicked(evt);
            }
        });

        mnuGSTRatesManagement.setText("GST Rates Management");
        mnuGSTRatesManagement.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuGSTRatesManagementActionPerformed(evt);
            }
        });
        mnuGST.add(mnuGSTRatesManagement);

        jMenuBar1.add(mnuGST);

        mnuReports.setText("Reports");
        mnuReports.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jMenuBar1.add(mnuReports);

        mnuSalesAccount.setText("Sales Account");
        mnuSalesAccount.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jMenuBar1.add(mnuSalesAccount);

        mnuCustomers.setText("Customers");
        mnuCustomers.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        mnuCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCustomersMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuCustomers);

        mnuDealerAccount.setText("Dealer Account");
        mnuDealerAccount.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jMenuBar1.add(mnuDealerAccount);

        mnuAbout.setText("About");
        mnuAbout.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jMenuBar1.add(mnuAbout);

        mnuClose.setText("Close");
        mnuClose.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        mnuClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mnuCloseMouseClicked(evt);
            }
        });
        jMenuBar1.add(mnuClose);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1282, 584));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    //Program to get license details
    String Company;
    public void getLicenseDetails(){
        try{
            String sql="Select * from Company";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){                
                Company=rs.getString("c_name");
                lblLicenseDetails.setText("Licensed to : "+Company);
            }
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"getLicenseDettails() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);  
        getLicenseDetails();
    }//GEN-LAST:event_formWindowOpened

    private void mnuCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCloseMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_mnuCloseMouseClicked

    private void lblUserMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseClicked
        // TODO add your handling code here:
        ManageCompany.getObj().setVisible(true);
    }//GEN-LAST:event_lblUserMouseClicked

    private void lblProductMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseClicked
        // TODO add your handling code here:
        ManageProducts.getObj().setVisible(true);
    }//GEN-LAST:event_lblProductMouseClicked

    private void lblUserMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/manage_user_hover.png"));
        lblUser.setIcon(II);
    }//GEN-LAST:event_lblUserMouseEntered

    private void lblUserMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblUserMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/manage_user.png"));
        lblUser.setIcon(II);
    }//GEN-LAST:event_lblUserMouseExited

    private void lblProductMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/product_hover.png"));
        lblProduct.setIcon(II);
    }//GEN-LAST:event_lblProductMouseEntered

    private void lblProductMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblProductMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/product.png"));
        lblProduct.setIcon(II);
    }//GEN-LAST:event_lblProductMouseExited

    private void lblSalesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/sales_hover.png"));
        lblSales.setIcon(II);
    }//GEN-LAST:event_lblSalesMouseEntered

    private void lblSalesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/sales.png"));
        lblSales.setIcon(II);
    }//GEN-LAST:event_lblSalesMouseExited

    private void lblReportsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/data_table_hover.png"));
        lblReports.setIcon(II);
    }//GEN-LAST:event_lblReportsMouseEntered

    private void lblReportsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/data_table.png"));
        lblReports.setIcon(II);
    }//GEN-LAST:event_lblReportsMouseExited

    private void lblSalesAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesAccountMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/notebook_hover.png"));
        lblSalesAccount.setIcon(II);
    }//GEN-LAST:event_lblSalesAccountMouseEntered

    private void lblSalesAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesAccountMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/notebook.png"));
        lblSalesAccount.setIcon(II);
    }//GEN-LAST:event_lblSalesAccountMouseExited

    private void lblCustomersMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/Customer_Male_Light_128px_533992_easyiconnet_hover.png"));
        lblCustomers.setIcon(II);
    }//GEN-LAST:event_lblCustomersMouseEntered

    private void lblCustomersMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/Customer_Male_Light_128px_533992_easyiconnet.png"));
        lblCustomers.setIcon(II);
    }//GEN-LAST:event_lblCustomersMouseExited

    private void lblDealersAccountMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDealersAccountMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/dealer_hover.png"));
        lblDealersAccount.setIcon(II);
    }//GEN-LAST:event_lblDealersAccountMouseEntered

    private void lblDealersAccountMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDealersAccountMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/dealer.png"));
        lblDealersAccount.setIcon(II);
    }//GEN-LAST:event_lblDealersAccountMouseExited

    private void lblAboutMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseEntered
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/help_hover.png"));
        lblAbout.setIcon(II);
    }//GEN-LAST:event_lblAboutMouseEntered

    private void lblAboutMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblAboutMouseExited
        // TODO add your handling code here:
        ImageIcon II=new ImageIcon(getClass().getResource("/coders/images/help.png"));
        lblAbout.setIcon(II);
    }//GEN-LAST:event_lblAboutMouseExited

    private void lblSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSalesMouseClicked
        // TODO add your handling code here:
        ManageSales.getObj().setVisible(true);
        //ManageSales ms=new ManageSales();ms.setVisible(true);
    }//GEN-LAST:event_lblSalesMouseClicked

    private void lblCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblCustomersMouseClicked
        // TODO add your handling code here:
        ManageCustomer.getObj().setVisible(true);
    }//GEN-LAST:event_lblCustomersMouseClicked

    private void mnuSalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuSalesMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuSalesMouseClicked

    private void mnuProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuProductsMouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_mnuProductsMouseClicked

    private void mnuCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuCustomersMouseClicked
        // TODO add your handling code here:
        ManageCustomer.getObj().setVisible(true);
    }//GEN-LAST:event_mnuCustomersMouseClicked

    private void lblReportsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblReportsMouseClicked
        // TODO add your handling code here:
        Reports.getObj().setVisible(true);
    }//GEN-LAST:event_lblReportsMouseClicked

    private void mnuPurchaseInwardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPurchaseInwardActionPerformed
        // TODO add your handling code here:
        PurchaseInvoice.getObj().setVisible(true);
    }//GEN-LAST:event_mnuPurchaseInwardActionPerformed

    private void mnuDirectProductManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuDirectProductManagementActionPerformed
        // TODO add your handling code here:
        ManageProducts.getObj().setVisible(true);
    }//GEN-LAST:event_mnuDirectProductManagementActionPerformed

    private void mnuPosTerminalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuPosTerminalActionPerformed
        // TODO add your handling code here:
        ManageSales.getObj().setVisible(true);
    }//GEN-LAST:event_mnuPosTerminalActionPerformed

    private void mnuManageCompanyDetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuManageCompanyDetailsActionPerformed
        // TODO add your handling code here:
        ManageCompany.getObj().setVisible(true);
    }//GEN-LAST:event_mnuManageCompanyDetailsActionPerformed

    private void mnuGSTMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuGSTMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuGSTMouseClicked

    private void mnuPurchaseReturnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mnuPurchaseReturnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuPurchaseReturnMouseClicked

    private void mnuSalesReturnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuSalesReturnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mnuSalesReturnActionPerformed

    private void mnuGSTRatesManagementActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuGSTRatesManagementActionPerformed
        // TODO add your handling code here:
        GSTRatesManagement.getObj().setVisible(true);
    }//GEN-LAST:event_mnuGSTRatesManagementActionPerformed

    private void lblDealersAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblDealersAccountMouseClicked
        // TODO add your handling code here:
        ManageDealer.getObj().setVisible(true);
    }//GEN-LAST:event_lblDealersAccountMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dashboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try{
                    Thread.sleep(4500);
                }
                catch(Exception e){
                    
                }
                new Dashboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblAbout;
    private javax.swing.JLabel lblCustomers;
    private javax.swing.JLabel lblDealersAccount;
    private javax.swing.JLabel lblLicenseDetails;
    private javax.swing.JLabel lblProduct;
    private javax.swing.JLabel lblProductName;
    private javax.swing.JLabel lblReports;
    private javax.swing.JLabel lblSales;
    private javax.swing.JLabel lblSalesAccount;
    private javax.swing.JLabel lblUser;
    private javax.swing.JMenu mnuAbout;
    private javax.swing.JMenu mnuClose;
    private javax.swing.JMenu mnuCompany;
    private javax.swing.JMenu mnuCustomers;
    private javax.swing.JMenu mnuDealerAccount;
    private javax.swing.JMenuItem mnuDirectProductManagement;
    private javax.swing.JMenu mnuGST;
    private javax.swing.JMenuItem mnuGSTRatesManagement;
    private javax.swing.JMenuItem mnuManageCompanyDetails;
    private javax.swing.JMenuItem mnuPosTerminal;
    private javax.swing.JMenu mnuProducts;
    private javax.swing.JMenuItem mnuPurchaseInward;
    private javax.swing.JMenuItem mnuPurchaseReturn;
    private javax.swing.JMenu mnuReports;
    private javax.swing.JMenu mnuSales;
    private javax.swing.JMenu mnuSalesAccount;
    private javax.swing.JMenuItem mnuSalesReturn;
    // End of variables declaration//GEN-END:variables
}
