/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coders.quickbill;

import javax.swing.JFrame;

/**
 *
 * @author sunny
 */
public class Reports extends javax.swing.JFrame {

    /**
     * Creates new form Reports
     */
    public Reports() {
        initComponents();
    }
    //Program to set one instance of Sales Form
    private static Reports obj=null;
    public static Reports getObj(){
        if(obj==null){
            obj=new Reports();
        }
        return obj;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ReportsjDesktopPane = new javax.swing.JDesktopPane();
        jMenuBar2 = new javax.swing.JMenuBar();
        mnuReports = new javax.swing.JMenu();
        mnuOverallSales = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        mnuCashSales = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        mnuCreditBalance = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Reports");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        mnuReports.setText("Reports");

        mnuOverallSales.setText("Overall Sales Report");
        mnuOverallSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuOverallSalesActionPerformed(evt);
            }
        });
        mnuReports.add(mnuOverallSales);
        mnuReports.add(jSeparator1);

        mnuCashSales.setText("Cash Sales Report");
        mnuCashSales.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCashSalesActionPerformed(evt);
            }
        });
        mnuReports.add(mnuCashSales);
        mnuReports.add(jSeparator2);

        mnuCreditBalance.setText("Credit Balance Report");
        mnuCreditBalance.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnuCreditBalanceActionPerformed(evt);
            }
        });
        mnuReports.add(mnuCreditBalance);

        jMenuBar2.add(mnuReports);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportsjDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 1110, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(ReportsjDesktopPane, javax.swing.GroupLayout.DEFAULT_SIZE, 469, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1120, 520));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void mnuCashSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCashSalesActionPerformed
        // TODO add your handling code here:
        CashSalesReportJInternalFrame csrjf=new CashSalesReportJInternalFrame();
        ReportsjDesktopPane.add(csrjf);
        csrjf.show();
    }//GEN-LAST:event_mnuCashSalesActionPerformed

    private void mnuOverallSalesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuOverallSalesActionPerformed
        // TODO add your handling code here:
        SalesReportJInternalFrame njf=new SalesReportJInternalFrame();
        ReportsjDesktopPane.add(njf);
        njf.show();
    }//GEN-LAST:event_mnuOverallSalesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);     
    }//GEN-LAST:event_formWindowOpened

    private void mnuCreditBalanceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnuCreditBalanceActionPerformed
        // TODO add your handling code here:
        CreditBalanceReportJInternalFrame cbrjf=new CreditBalanceReportJInternalFrame();
        ReportsjDesktopPane.add(cbrjf);
        cbrjf.show();
    }//GEN-LAST:event_mnuCreditBalanceActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reports.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reports().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane ReportsjDesktopPane;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JMenuItem mnuCashSales;
    private javax.swing.JMenuItem mnuCreditBalance;
    private javax.swing.JMenuItem mnuOverallSales;
    private javax.swing.JMenu mnuReports;
    // End of variables declaration//GEN-END:variables
}
