/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package coders.quickbill;

import java.awt.Color;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import net.proteanit.sql.DbUtils;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author sunny
 */
public class ManageProducts extends javax.swing.JFrame {

    Connection conn=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    /**
     * Creates new form ManageProducts
     */
    public ManageProducts() {
        initComponents();
        conn=javaconnect.ConnectDB();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtProductID = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtBarcode = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtItemName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtDescription = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtQty = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnPrint = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRate = new javax.swing.JTextField();
        btnNew = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        txtCGST = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtSGST = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtIGST = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        cmbUnit = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        txtHSNCODE = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblManageProducts = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Manage Products - Coders Quickbill 2017");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(40, 40, 40));

        jPanel2.setBackground(new java.awt.Color(153, 51, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Product Details", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), java.awt.Color.white)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel1.setForeground(java.awt.Color.white);
        jLabel1.setText("Product ID");

        txtProductID.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel2.setForeground(java.awt.Color.white);
        jLabel2.setText("Barcode");

        txtBarcode.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtBarcode.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtBarcodeFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtBarcodeFocusLost(evt);
            }
        });
        txtBarcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBarcodeActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel3.setForeground(java.awt.Color.white);
        jLabel3.setText("Item Name");

        txtItemName.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtItemName.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtItemNameFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtItemNameFocusLost(evt);
            }
        });
        txtItemName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtItemNameKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtItemNameKeyReleased(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setText("Description");

        txtDescription.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtDescription.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtDescriptionFocusLost(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel5.setForeground(java.awt.Color.white);
        jLabel5.setText("Quantity");

        txtQty.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtQty.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtQtyFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtQtyFocusLost(evt);
            }
        });
        txtQty.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtQtyKeyPressed(evt);
            }
        });

        btnAdd.setBackground(java.awt.Color.green);
        btnAdd.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnAdd.setText("ADD");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnUpdate.setBackground(java.awt.Color.orange);
        btnUpdate.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnUpdate.setText("UPDATE");
        btnUpdate.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnDelete.setBackground(java.awt.Color.red);
        btnDelete.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnDelete.setText("DELETE");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnPrint.setBackground(java.awt.Color.white);
        btnPrint.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnPrint.setIcon(new javax.swing.ImageIcon(getClass().getResource("/coders/images/printer.png"))); // NOI18N
        btnPrint.setText("PRINT");
        btnPrint.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel6.setForeground(java.awt.Color.white);
        jLabel6.setText("Rate");

        txtRate.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtRateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtRateFocusLost(evt);
            }
        });

        btnNew.setBackground(java.awt.Color.cyan);
        btnNew.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        btnNew.setText("NEW");
        btnNew.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel7.setForeground(java.awt.Color.white);
        jLabel7.setText("CGST%");

        txtCGST.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtCGST.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCGSTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtCGSTFocusLost(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel8.setForeground(java.awt.Color.white);
        jLabel8.setText("SGST%");

        txtSGST.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtSGST.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSGSTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSGSTFocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel9.setForeground(java.awt.Color.white);
        jLabel9.setText("IGST%");

        txtIGST.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        txtIGST.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtIGSTFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtIGSTFocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        jLabel10.setForeground(java.awt.Color.white);
        jLabel10.setText("Unit");

        cmbUnit.setFont(new java.awt.Font("Ubuntu", 1, 13)); // NOI18N
        cmbUnit.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "--Select Unit--", "brl - Barrel", "box - Box", "can - Can", "cas - Case", "cg - Centigrams", "cl - Centilitres", "cm - Centimeters", "chn - Chain", "crt - Crate", "ccm - Cubic Centimeters", "cdm - Cubic Decimeters", "cuf - Cubic Feets", "cui - Cubic Inches", "cum - Cubic Meters", "cmm - Cubic Milimeters", "cuy - Cubic Yards", "dg - Decigrams", "dl - Deciliters", "dm - Decimeters", "doz - Dozen", "ea - Each", "ft - Feet", "fl - Flask", "gal - Galon", "gr - Grams", "grs - Gross", "hun - Hundreds", "in - Inches", "kg - Kilograms", "kl - Kiloliters", "kt - Kiloton", "knt - Knots", "l - Litres", "m - Meters", "mt - Metric Tons", "mg - Miligram", "oz - Ounce", "pc - Piece", "ton - Tons" }));
        cmbUnit.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cmbUnitFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                cmbUnitFocusLost(evt);
            }
        });

        jLabel11.setForeground(java.awt.Color.white);
        jLabel11.setText("HSN-CODE");

        txtHSNCODE.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtHSNCODEFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtHSNCODEFocusLost(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, 458, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtHSNCODE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtItemName))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 708, Short.MAX_VALUE)
                        .addComponent(btnNew)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPrint))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cmbUnit, 0, 265, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCGST, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtSGST, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtIGST, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescription)))
                .addContainerGap())
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnAdd, btnDelete, btnNew, btnPrint, btnUpdate});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(txtProductID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2)
                        .addComponent(txtBarcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtHSNCODE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtItemName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDescription, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(txtQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(cmbUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel6)
                        .addComponent(txtRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel7)
                        .addComponent(txtCGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8)
                        .addComponent(txtSGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(txtIGST, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnDelete)
                    .addComponent(btnPrint)
                    .addComponent(btnNew)))
        );

        tblManageProducts.setAutoCreateRowSorter(true);
        tblManageProducts.setBackground(new java.awt.Color(53, 53, 53));
        tblManageProducts.setFont(new java.awt.Font("Ubuntu", 0, 13)); // NOI18N
        tblManageProducts.setForeground(java.awt.Color.white);
        tblManageProducts.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tblManageProducts.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblManageProductsMouseClicked(evt);
            }
        });
        tblManageProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tblManageProductsKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tblManageProductsKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tblManageProducts);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1272, 539));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    //Program to set one instance of ManageProduct Form
    private static ManageProducts obj=null;
    public static ManageProducts getObj(){
        if(obj==null){
            obj=new ManageProducts();
        }
        return obj;
    }
    //Program to read Products Database
    public void readProducts(){
        try{
            String sql="Select pid as 'Product ID',p_barcode as 'Barcode',p_hsncode as 'HSN Code',p_itemName as 'Item Name',p_description as 'Description',"
                    + "p_qty as 'Quantity',p_unit as 'Unit',p_rate as 'Rate',p_cgst as 'CGST',p_sgst as 'SGST',p_igst as 'IGST' from Products";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            tblManageProducts.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();            
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"readProducts() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    //Program to set new Product ID
    int pid=0;
    public void setNewPID(){
        try{
            String sql="Select * from Products";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            while(rs.next()){
                pid=rs.getInt("pid");
            }
            pid++;
            txtProductID.setText(String.valueOf(pid));
            txtBarcode.setText("");
            txtHSNCODE.setText("");
            txtItemName.setText("");
            txtDescription.setText("");
            txtQty.setText("0");
            cmbUnit.setSelectedIndex(0);
            txtRate.setText("0");
            txtCGST.setText("0");
            txtSGST.setText("0");
            txtIGST.setText("0");
            txtBarcode.requestFocus();
            pst.close(); 
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"setPID() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        readProducts();
        setNewPID();
    }//GEN-LAST:event_formWindowOpened
    
    private void btnNewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewActionPerformed
        // TODO add your handling code here:
        setNewPID();
    }//GEN-LAST:event_btnNewActionPerformed

    //Program to add Product to database
    public void addProduct(){
        try{
            String sql="insert into Products(p_barcode,p_itemName,p_description,p_qty,p_unit,p_rate,p_cgst,p_sgst,p_igst,p_hsncode)"
                    + "values(?,?,?,?,?,?,?,?,?,?)";
            pst=conn.prepareStatement(sql);
            pst.setString(1,txtBarcode.getText());
            pst.setString(2,txtItemName.getText());
            pst.setString(3, txtDescription.getText());
            pst.setString(4, txtQty.getText());
            pst.setString(5, cmbUnit.getSelectedItem().toString());
            pst.setString(6, txtRate.getText());
            pst.setString(7, txtCGST.getText());
            pst.setString(8, txtSGST.getText());
            pst.setString(9, txtIGST.getText());
            pst.setInt(10, Integer.parseInt(txtHSNCODE.getText()));
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Product Added to Database Successfully","Product Saved",JOptionPane.INFORMATION_MESSAGE);
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"addProduct() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        addProduct();
        readProducts();
        setNewPID();
    }//GEN-LAST:event_btnAddActionPerformed
    
    //Program to update Product data
    public void updtProduct(){
        try{
            String sql="update Products set p_barcode='"+txtBarcode.getText()+"', p_itemName='"+txtItemName.getText()+"',"
                    + "p_description='"+txtDescription.getText()+"',p_qty='"+txtQty.getText()+"',p_unit='"+cmbUnit.getSelectedItem().toString()+"',p_rate='"+txtRate.getText()+"',"
                    + "p_cgst='"+txtCGST.getText()+"',p_sgst='"+txtSGST.getText()+"',p_igst='"+txtIGST.getText()+"',p_hsncode='"+Integer.parseInt(txtHSNCODE.getText())+"'"
                    + "where pid='"+txtProductID.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Data Updated Successfully","Data Updated",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e,"updtProduct() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        updtProduct();
        readProducts();
        setNewPID();
    }//GEN-LAST:event_btnUpdateActionPerformed

    //Program to Remove Product
    public void delProduct(){
        try{
            String sql="Delete from Products where pid='"+txtProductID.getText()+"'";
            pst=conn.prepareStatement(sql);
            pst.execute();
            pst.close();
            JOptionPane.showMessageDialog(null, "Product Data Removed Successfully","Data Removed",JOptionPane.INFORMATION_MESSAGE);
        }
        catch(SQLException | HeadlessException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        delProduct();
        readProducts();
        setNewPID();
    }//GEN-LAST:event_btnDeleteActionPerformed

    //Program to get selected data to fields
    public void getTblDataToField(){
        try{
            int row=tblManageProducts.getSelectedRow();
            String ProdID=tblManageProducts.getModel().getValueAt(row, 0).toString();
            String sql="Select * from Products where pid='"+ProdID+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtProductID.setText(rs.getString("pid"));
                txtBarcode.setText(rs.getString("p_barcode"));
                txtHSNCODE.setText(rs.getString("p_hsncode"));
                txtItemName.setText(rs.getString("p_itemName"));
                txtDescription.setText(rs.getString("p_description"));
                txtQty.setText(rs.getString("p_qty"));
                cmbUnit.setSelectedItem(rs.getString("p_unit"));
                txtRate.setText(rs.getString("p_rate"));
                txtCGST.setText(rs.getString("p_cgst"));
                txtSGST.setText(rs.getString("p_sgst"));
                txtIGST.setText(rs.getString("p_igst"));
                btnAdd.setEnabled(false);
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);                
            }
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    private void tblManageProductsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblManageProductsMouseClicked
        // TODO add your handling code here:
        getTblDataToField();
    }//GEN-LAST:event_tblManageProductsMouseClicked

    //Program on barcode scan
    public void barcodeScan(){
        try{
            String sql="Select * from Products where p_barcode='"+txtBarcode.getText()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                txtProductID.setText(rs.getString("pid"));
                txtBarcode.setText(rs.getString("p_barcode"));
                txtHSNCODE.setText(rs.getString("p_hsncode"));
                txtItemName.setText(rs.getString("p_itemName"));
                txtDescription.setText(rs.getString("p_description"));
                txtQty.setText(rs.getString("p_qty"));
                cmbUnit.setSelectedItem(rs.getString("p_unit"));
                txtRate.setText(rs.getString("p_rate"));
                txtCGST.setText(rs.getString("p_cgst"));
                txtSGST.setText(rs.getString("p_sgst"));
                txtIGST.setText(rs.getString("p_igst"));
                btnAdd.setEnabled(false);
                btnUpdate.setEnabled(true);
                btnDelete.setEnabled(true);                
            }
            else{
                //txtBarcode.setText("");
                txtHSNCODE.setText("");
                txtItemName.setText("");
                txtDescription.setText("");
                txtQty.setText("0");
                cmbUnit.setSelectedItem("--Select Unit--");
                txtRate.setText("0");
                txtCGST.setText("0");
                txtSGST.setText("0");
                txtIGST.setText("0");
                btnAdd.setEnabled(true);
                btnUpdate.setEnabled(false);
                btnDelete.setEnabled(false);
                JOptionPane.showMessageDialog(null, "Barcode not found. Add new to record.","ATTENTION!",JOptionPane.INFORMATION_MESSAGE);
            }   
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"barcodescan() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtBarcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBarcodeActionPerformed
        // TODO add your handling code here:
        barcodeScan();
    }//GEN-LAST:event_txtBarcodeActionPerformed

    //Program to find product on name entry
    public void findProduct(){
        try{
            String KeyVal=txtItemName.getText();
            String sql="Select * from Products where p_itemName LIKE ?";
            pst=conn.prepareStatement(sql);
            pst.setString(1,"%"+KeyVal + "%");
            rs=pst.executeQuery();
            tblManageProducts.setModel(DbUtils.resultSetToTableModel(rs));
            pst.close();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, e,"findProduct() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }
    private void txtItemNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyReleased
        // TODO add your handling code here:
        findProduct();
    }//GEN-LAST:event_txtItemNameKeyReleased

    //Program to load selected product to fields
    public void loadSelect(){
        try{
            txtProductID.setText(tblManageProducts.getValueAt(0, 0).toString());
            txtBarcode.setText(tblManageProducts.getValueAt(0, 1).toString());
            txtHSNCODE.setText(tblManageProducts.getValueAt(0, 2).toString());
            txtItemName.setText(tblManageProducts.getValueAt(0, 3).toString());
            txtDescription.setText(tblManageProducts.getValueAt(0, 4).toString());
            txtQty.setText(tblManageProducts.getValueAt(0, 5).toString());
            cmbUnit.setSelectedItem(tblManageProducts.getValueAt(0, 6).toString());
            txtRate.setText(tblManageProducts.getValueAt(0, 7).toString());
            txtCGST.setText(tblManageProducts.getValueAt(0, 8).toString());
            txtSGST.setText(tblManageProducts.getValueAt(0, 9).toString());
            txtIGST.setText(tblManageProducts.getValueAt(0, 10).toString());
        }
        catch(Exception e){
            JOptionPane.showMessageDialog(null, e,"loadSelect() Exception",JOptionPane.ERROR_MESSAGE);
        }
    } 
    private void txtItemNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtItemNameKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            loadSelect();
        }
    }//GEN-LAST:event_txtItemNameKeyPressed

    private void txtQtyKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtQtyKeyPressed
        // TODO add your handling code here:
        char c=evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||(c==KeyEvent.VK_DELETE)||(c==KeyEvent.VK_PERIOD))){
            evt.consume();
            getToolkit().beep();
            txtQty.setBackground(Color.RED);
        }
        else{
            txtQty.setBackground(Color.yellow);
        }
    }//GEN-LAST:event_txtQtyKeyPressed

    private void txtQtyFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusGained
        // TODO add your handling code here:
        txtQty.setBackground(Color.yellow);
    }//GEN-LAST:event_txtQtyFocusGained

    private void txtQtyFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtQtyFocusLost
        // TODO add your handling code here:
        txtQty.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtQtyFocusLost

    private void txtBarcodeFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarcodeFocusGained
        // TODO add your handling code here:
        txtBarcode.setBackground(Color.yellow);
    }//GEN-LAST:event_txtBarcodeFocusGained

    private void txtBarcodeFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtBarcodeFocusLost
        // TODO add your handling code here:
        txtBarcode.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtBarcodeFocusLost

    private void txtItemNameFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusGained
        // TODO add your handling code here:
        txtItemName.setBackground(Color.yellow);
    }//GEN-LAST:event_txtItemNameFocusGained

    private void txtItemNameFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtItemNameFocusLost
        // TODO add your handling code here:
        txtItemName.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtItemNameFocusLost

    private void txtDescriptionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusGained
        // TODO add your handling code here:
        txtDescription.setBackground(Color.yellow);
    }//GEN-LAST:event_txtDescriptionFocusGained

    private void txtDescriptionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtDescriptionFocusLost
        // TODO add your handling code here:
        txtDescription.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtDescriptionFocusLost

    private void txtRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRateFocusGained
        // TODO add your handling code here:
        txtRate.setBackground(Color.yellow);
    }//GEN-LAST:event_txtRateFocusGained

    private void txtRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtRateFocusLost
        // TODO add your handling code here:
        txtRate.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtRateFocusLost

    private void txtCGSTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCGSTFocusGained
        // TODO add your handling code here:
        txtCGST.setBackground(Color.yellow);
    }//GEN-LAST:event_txtCGSTFocusGained

    private void txtCGSTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCGSTFocusLost
        // TODO add your handling code here:
        txtCGST.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtCGSTFocusLost

    private void txtSGSTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSGSTFocusGained
        // TODO add your handling code here:
        txtSGST.setBackground(Color.yellow);
    }//GEN-LAST:event_txtSGSTFocusGained

    private void txtSGSTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSGSTFocusLost
        // TODO add your handling code here:
        txtSGST.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtSGSTFocusLost

    private void txtIGSTFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIGSTFocusGained
        // TODO add your handling code here:
        txtIGST.setBackground(Color.yellow);
    }//GEN-LAST:event_txtIGSTFocusGained

    private void txtIGSTFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtIGSTFocusLost
        // TODO add your handling code here:
        txtIGST.setBackground(Color.WHITE);
    }//GEN-LAST:event_txtIGSTFocusLost

    private void cmbUnitFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbUnitFocusGained
        // TODO add your handling code here:
        cmbUnit.setBackground(Color.yellow);
    }//GEN-LAST:event_cmbUnitFocusGained

    private void cmbUnitFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cmbUnitFocusLost
        // TODO add your handling code here:
        cmbUnit.setBackground(Color.WHITE);
    }//GEN-LAST:event_cmbUnitFocusLost

    private void tblManageProductsKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblManageProductsKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_tblManageProductsKeyPressed

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        obj=null;
    }//GEN-LAST:event_formWindowClosing
    //Program to Print Product List
    public void printOptions(){
        try{
            String sql="Select * from Products,Company";
            JasperDesign jd= JRXmlLoader.load("src/coders/reports/a4ProductList.jrxml");
            JRDesignQuery qry=new JRDesignQuery();
            qry.setText(sql);
            jd.setQuery(qry);
            JasperReport jr= JasperCompileManager.compileReport(jd);
            JasperPrint jp=JasperFillManager.fillReport(jr, null,conn);
            JasperViewer.viewReport(jp,false);
        }catch(JRException e){
            JOptionPane.showMessageDialog(null, e,"printOption() Exception",JOptionPane.ERROR_MESSAGE);
        }
    }    
    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
        // TODO add your handling code here:
        printOptions();
    }//GEN-LAST:event_btnPrintActionPerformed

    private void txtHSNCODEFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHSNCODEFocusGained
        // TODO add your handling code here:
        txtHSNCODE.setBackground(Color.yellow);
    }//GEN-LAST:event_txtHSNCODEFocusGained

    private void txtHSNCODEFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtHSNCODEFocusLost
        // TODO add your handling code here:
        txtHSNCODE.setBackground(Color.white);
    }//GEN-LAST:event_txtHSNCODEFocusLost

    private void tblManageProductsKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tblManageProductsKeyReleased
        // TODO add your handling code here:
        if(evt.getKeyCode()==KeyEvent.VK_UP||evt.getKeyCode()==KeyEvent.VK_DOWN){
            getTblDataToField();
        }
    }//GEN-LAST:event_tblManageProductsKeyReleased

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManageProducts.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManageProducts().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnNew;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbUnit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblManageProducts;
    private javax.swing.JTextField txtBarcode;
    private javax.swing.JTextField txtCGST;
    private javax.swing.JTextField txtDescription;
    private javax.swing.JTextField txtHSNCODE;
    private javax.swing.JTextField txtIGST;
    private javax.swing.JTextField txtItemName;
    private javax.swing.JTextField txtProductID;
    private javax.swing.JTextField txtQty;
    private javax.swing.JTextField txtRate;
    private javax.swing.JTextField txtSGST;
    // End of variables declaration//GEN-END:variables
}
